### ISSUE TITLE
new device request: OnePlus 6

### ISSUE THREAD

**Issue by realroot2185** [AXP-OS/issue-tracker#23]
### Device vendor

OnePlus

### Device model

6

### Device codename

enchilada

### LineageOS device tree and/or WIKI page

https://wiki.lineageos.org/devices/enchilada

### Supported by DivestOS already?

yes

### Prepared to support?

- [X] yes, I've joined AND linked this issue there

**Comment by realroot2185** [comment]
Note similar device OnePlus 6T is already supported.

**Comment by steadfasterX** [comment]
## current implementation state of this device request

:tada: **Congratulations!**
Your device request has been accepted after an initial (rough) check. This means that the standard process for introducing this device into AXP.OS will now begin. The following overview shows the current status. Please avoid asking for any ETA's (Estimated Time of Arrival).

_Please note: Even if this does not happen often, it may turn out during this process that a device CANNOT be included after all. This may be for technical reasons, but may also be due to a lack of co-operation on the part of the requester._

**This is a status page for information purposes only and will be updated by the AXP.OS team on an ongoing basis.**

**There is no action required from your site unless you get contacted.**

- [ ] update [AXP.OS manifest](https://github.com/AXP-OS/manifest)
- [ ] setup [vendor/firmware](https://code.binbash.rocks:8443/AXP.OS/vendor_firmware)
- [ ] setup [automation repo](https://github.com/sfX-android/automation_scripts/tree/ansible/roles/axp)
- [ ] setup semaphore
- [ ] compile
- [ ] **_OPTIONAL_** (_only required when a device is NOT(!) supported by DOS_):
    - [ ] enable [verity](https://github.com/AXP-OS/build/blob/a4536167f37731618f83045b9996cf9b4552520b/Scripts/Common/Enable_Verity.sh#L293)
    - [ ] if kernel defconfig can't be found: add it manually to [getDefconfig](https://github.com/AXP-OS/build/blob/a1508ef817cded844cb984131e0868b2cbc84801/Scripts/Common/Functions.sh#L873)
    - [ ] if it does not _compile_: follow [generate & test kernel patches](https://github.com/AXP-OS/build/wiki/port-guide#generate--test-kernel-patches) and add exceptions to [Fix_CVE_Patchers.sh](https://github.com/AXP-OS/build/blob/axp/Scripts/Common/Fix_CVE_Patchers.sh)
    - [ ] if it does not _boot_: overwrite the device default CONFIG (e.g. like [this](https://github.com/sfX-android/automation_scripts/blob/d20f7dce494c72e956eb4e7efde2c0705cb969b3/roles/axp/common/templates/divested.vars.j5y17lte.j2#L13C8-L13C28))
- [ ] test all AXP.OS [core features](https://github.com/AXP-OS/build/wiki/Features)
- [ ] if applicable: test bootloader re-lock
- [ ] add device to [the AXP.OS wiki](https://github.com/AXP-OS/build/wiki)
- [ ] prepare DL+OTA server
- [ ] provide a public beta version
- [ ] update website
- [ ] announce on XDA

**Comment by realroot2185** [comment]
I bought this used phone to use linux.
Since support there is not perfect and I may need android app e.g. banking app I thought about dual booting (linux and android) but I am having problems.
After some time I lose the bootloader mode and android stopped working (lineage in this case). 
I did factory reset some times now and after I have to update stock OS even for linux.

So I do not know if I can test this.
At the moment I will try to use only linux.
Sorry.

In the future once I get things working etc. I may try to use AXP-OS too.

**Comment by steadfasterX** [comment]
if someone wants to see this coming and able to help with testing: re-open the issue and/or comment.

**Comment by Sneethe** [comment]
I will help with testing. @steadfasterX 
Please re-open.

**Comment by rocky-184** [comment]
- [Y] current ASB patch - System (`Android Settings -> Info/About -> Android Version` must be current)
- [Y] current ASB patch - Kernel (`Android Settings -> Info/About -> Kernel version -> build date` must be current. Kernel version must have `dos.pXXX` inside the version string)
- [Y] SELinux enforced (`Android Settings -> Privacy -> Trust`)
- [Y] Encryption enforced (`Android Settings -> Privacy -> Trust`)
- [Y] pre-rooted (`Magisk App -> "Magisk" must be shown as "installed"`)
- [Y] signature spoofing support (see Enable [Google Support](https://github.com/AXP-OS/build/wiki/Setup#optional-activate-google-support))
- [Y] microG included (`microG Settings -> Selftest -> ensure all checkboxes are ticked`)
- [Y] current [Google Play Store](https://github.com/AXP-OS/microg-phonesky-iap-support/releases) included
- [ ] Enable WireGuard VPN Kernel module (`Wireguard App -> grant root -> enable kernel support in settings`)
- [Y] OpenEUICC app included for devices supporting euicc ([Enable eSIM](https://divestos.org/pages/faq#activateEUICC))
- [Y] locking the bootloader on supported devices (see the device [wiki page](https://github.com/AXP-OS/build/wiki#installation-guides))
- [Y] Home Launcher Neo Launcher included
- [Y] extended list of F-Droid repositories (`F-Droid App -> Repositories -> find molly, nailyk, threema, futo_org`)
- [Y] AuroraStore App included
- [ ] boot debug log added (`adb shell ls -la [DEVICE-BOOT-DEBUG-PATH]/boot_debug` [DEVICE-BOOT-DEBUG-PATH] is defined in the [install guide](https://github.com/AXP-OS/build/wiki#installation-guides). Add the output in a comment)
- [Y] OTA update

**Comment by rocky-184** [comment]
Output from boot debug log:

PS C:\Users\David\Downloads> adb shell
OnePlus6:/ $ su
OnePlus6:/ # ls -la /mnt/vendor/persist/boot_debug
total 1764
drwxrwx---  2 system system   4096 2024-12-30 20:34 .
drwxrwx--x 29 root   system   4096 1974-04-23 07:20 ..
-rw-------  1 system system      0 1974-04-23 07:20 crash.txt
-rw-------  1 system system 348160 2024-12-30 20:34 full.txt
-rw-------  1 system system 531002 2024-12-30 20:34 full.txt.1
-rw-------  1 system system      0 1974-04-23 07:20 kernel.txt
-rw-------  1 system system 143360 2024-12-30 20:34 selinux.txt
-rw-------  1 system system 204991 2024-12-30 20:14 selinux.txt.1
OnePlus6:/ #

**Comment by steadfasterX** [comment]
@rocky-184 greatly appreciated, thanks!
